# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20200623_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='new_outbreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='surveillance_type',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Passive', b'Passive')], max_length=30, null=True),
        ),
    ]
