# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20200623_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasereport',
            old_name='incedent_rate',
            new_name='incedence_rate',
        ),
        migrations.RenameField(
            model_name='diseasereport',
            old_name='moditity_rate',
            new_name='mobidity_rate',
        ),
    ]
