# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20200626_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='abattoir',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='permits',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transportfleet',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vetinfraindustry',
            name='approve',
            field=models.CharField(blank=True, choices=[(b'Approve', b'Approve'), (b'Disapprove', b'Disapprove')], max_length=30, null=True),
        ),
    ]
