# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20200626_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permits',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permits',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
