# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20200702_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permits',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permits',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
