# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-06 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20200702_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinical',
            old_name='approve',
            new_name='approve_one',
        ),
    ]
