# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=30)),
                ('sent_by', models.CharField(blank=True, max_length=30)),
                ('edited_by', models.CharField(blank=True, max_length=30)),
                ('date_sent', models.DateField(auto_now_add=True, null=True)),
                ('date_edited', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
