# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_noticeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='message',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
