# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0018_auto_20200727_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
