# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_noticeboard_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='read_by',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
