# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_auto_20200802_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='No_animal_producer',
            new_name='no_animal_producer',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='No_of_borns',
            new_name='no_of_borns',
        ),
    ]
