# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0023_auto_20200802_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='abattoir',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='clinical',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='lab',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='locality',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='permits',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='production',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='transportfleet',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='vetinfraindustry',
            name='comment',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
