# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_auto_20200802_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abattoir',
            name='month',
        ),
        migrations.RemoveField(
            model_name='abattoir',
            name='year',
        ),
        migrations.RemoveField(
            model_name='diseasereport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='diseasereport',
            name='year',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='month',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='year',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='month',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='year',
        ),
        migrations.RemoveField(
            model_name='permits',
            name='month',
        ),
        migrations.RemoveField(
            model_name='permits',
            name='year',
        ),
        migrations.RemoveField(
            model_name='production',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transportfleet',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transportfleet',
            name='year',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='month',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='year',
        ),
        migrations.RemoveField(
            model_name='vetinfraindustry',
            name='month',
        ),
        migrations.RemoveField(
            model_name='vetinfraindustry',
            name='year',
        ),
    ]
